### ISSUE TITLE
journalbeat eats lots of memory occasionally

### ISSUE THREAD

**Issue by bergerx** [mheese/journalbeat#88]
We use journalbeat to push all systemd logs to a kafka topic. Our journalbeat version is `journalbeat version 5.1.1 (amd64), libbeat 5.1.1` running on `CentOS Linux release 7.3.1611 (Core)`.

I see many nodes are consuming memory more than 1G, and they are up for a week.

![image](https://user-images.githubusercontent.com/45531/28519960-4f714ec6-7076-11e7-9cd2-eca0019257e9.png)

Here  is an example config from our prod:
```yaml
journalbeat:
  seek_position: cursor
name: journalbeat
output.kafka:
  enabled: true
  hosts: ["broker.confluent-elk.l4lb.thisdcos.directory:9092"]
  topic: 'journalbeat'
  required_acks: 1
  max_message_bytes: 1000000
logging.to_files: true
logging.files:
  path: /var/log/journalbeat
  name: journalbeat
```

**Comment by nicorevin** [comment]
Hi!

It can be related to the issue fixed here https://github.com/mheese/journalbeat/commit/28be704040058a70ddac1728fea0ba54bbe0009e .
You are using a 6-month old release. Please consider upgrading. :)

**Comment by mheese** [comment]
@bergerx, hm, several questions for you:

1. do you mean that it has been slowly increasing in the last week? do you expect a leak?
2. do you get similar/same results if you don't use `kafka` as output?
3. have you tried with later versions of journalbeat?
4. what are your journald settings?

Personally, I haven't experienced/observed any memory leaks (which does not mean that there are none), however, I am not using Kafka as output (any longer), I'm shipping to logstash directly. The difficulty is that the biggest part of this program is handled by `libbeat` from Elastic, and we are not testing all the outputs.

If you can help me to narrow it down, I'm more than happy to assist.

**Comment by bergerx** [comment]
Thanks for the replies.

@nicorevin:

> You are using a 6-month old release. Please consider upgrading. :)

We'll likely be upgrading it this week.

@mheese: 

> 1. do you mean that it has been slowly increasing in the last week? do you expect a leak?

I guess it's slowly increasing but I can't be sure without a metric collection in place. We are starting journalbeat as a systemd service and we'll start following systemd services' memory usage via cgroups, that'll tell us if this is or not. In the meantime, I limited it's memory to 50M with `MemoryLimit=50M` via systemd, so it will be killed by OOM if it starts using more memory than that and restarted by systemd :(

> 2. do you get similar/same results if you don't use kafka as output?

I'm not sure, we just realized that this happens in our long running beta clusters which i can't easily test this, but if this keeps being a problem we'll likely dive deeper.

> 3. have you tried with later versions of journalbeat?

We will.

> 4. what are your journald settings?

I guess it's the CentOS defaults, I don't think we tuned any journald configuration.

**Comment by nicorevin** [comment]
I've hit the same issue on random nodes. Journalbeat starts and in a few moments hits the 1 GB limit. When you raise the bar it will still hit it but less frequently. It affects only selected nodes. And it seems to be related to a lot of `EOF`s (rejections) from logstash and with the size of the messages...

Anyway it looks like a memory leak in libbeat.

Will get back when get more details.

**Comment by bergerx** [comment]
We've limited max memory of journalbeat service with 50mb (systemd MemoryLimit = 50M) in our cluster, here is memory signature from a small cluster:

![image](https://user-images.githubusercontent.com/45531/28909537-c7a1c69e-7820-11e7-8621-23ff7c7cce6e.png)

In the meantime I guess we also updated the journalbeat version to latest, I'll update after cheking its version.

**Comment by nicorevin** [comment]
@bergerx I've finally spotted the cause for such a huge memory consumption. The 5.5.2 release will fix it.

**Comment by mheese** [comment]
@nicorevin so what's the issue?

**Comment by nicorevin** [comment]
@mheese race detector turned on. fixed in https://github.com/mheese/journalbeat/commit/67d08bd9e7810888831902adffb82647335fe363

**Comment by mheese** [comment]
right... I remember that now

**Comment by bergerx** [comment]
I'm seeing improvement, but still not fully solved:
- **improvement**: i dont see the previous saw pattern
- **not solved**: journalctl can still use multi hundred MB memory,  as far as i see this happens on the nodes with many logs are waiting to be pushed. When I start journalbeat for the first time on a host, it tend to use more memory and doesn't give back the allocated memory even after the initial rush. restaring the service heps.

![image](https://user-images.githubusercontent.com/45531/31439195-ff67bd5a-ae93-11e7-8918-8098f3626c9e.png)

**Comment by bergerx** [comment]
Seems like the exessive part is from file caches, here is another graph with and without file caches:
![image](https://user-images.githubusercontent.com/45531/31446876-478e73b6-aea9-11e7-9b7e-b701bd95fc92.png)


Will be watching the graphs little bit more but i think we can close this one.
